// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numOfTry = Integer.parseInt(args[0]);
		int countUnderHalf = 0, countUpperHalf = 0;
		for (int i = 0; i < numOfTry; i++) {
			double randomNum = Math.random();
			if (randomNum > 0.5) countUpperHalf++;
			else countUnderHalf++;
		}
		System.out.println("> 0.5: " + countUpperHalf + " times");
		System.out.println("<= 0.5: " + countUnderHalf + " times");

		if (countUpperHalf != 0 && countUnderHalf != 0) {
			System.out.println("Ratio: " + ((double) (countUnderHalf) / countUpperHalf));
		}
	}
}
